# -*- coding: utf-8 -*-
"""PQS_IDS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E3taiylRsL47kcesjCgbqrKZrFaBph-Y
"""

# 1. Install system dependencies
!apt-get update && apt-get install -y cmake ninja-build libssl-dev tcpdump

# Commented out IPython magic to ensure Python compatibility.
# 2. Build liboqs (The core quantum engine)
# %cd /content
!rm -rf liboqs oqs-provider
!git clone --depth 1 https://github.com/open-quantum-safe/liboqs.git
# %cd liboqs
!cmake -GNinja -B build -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_SHARED_LIBS=ON
!ninja -C build install

# Commented out IPython magic to ensure Python compatibility.
# 3. Build oqs-provider (The bridge to OpenSSL)
# %cd /content
!git clone --depth 1 https://github.com/open-quantum-safe/oqs-provider.git
# %cd oqs-provider
!liboqs_DIR=/usr/local cmake -GNinja -B _build
!ninja -C _build

# 4. Create the modules directory and move the provider
!mkdir -p /usr/local/lib/ossl-modules
!find _build -name "oqsprovider.so" -exec cp {} /usr/local/lib/ossl-modules/ \;

import os
# Set paths for the current session
os.environ['OPENSSL_MODULES'] = '/usr/local/lib/ossl-modules'
os.environ['LD_LIBRARY_PATH'] = '/usr/local/lib:' + os.environ.get('LD_LIBRARY_PATH', '')

print("Checking for Quantum Provider...")
!openssl list -providers -provider oqsprovider

# Generate the Private Key
!openssl genpkey -provider oqsprovider -provider default \
    -algorithm mldsa65 -out pqc_ca.key

# Generate the Certificate
!openssl req -x509 -new -provider oqsprovider -provider default \
    -key pqc_ca.key -out pqc_ca.crt -nodes -days 365 \
    -subj "/C=BD/ST=Dhaka/L=Dhaka/O=NoshinLab/CN=QuantumIDS.local"

import subprocess
import time
import os

# 1. Cleanup: Kill any lingering processes from previous runs
os.system("pkill -9 openssl")
os.system("pkill -9 tcpdump")
time.sleep(1)

print("--- Starting Quantum Sandbox ---")

# 2. Start the Quantum Server in the background
# -propquery forces the use of the OQS provider for the handshake
server_cmd = [
    "openssl", "s_server",
    "-provider", "oqsprovider", "-provider", "default",
    "-propquery", "provider=oqsprovider",
    "-cert", "pqc_ca.crt", "-key", "pqc_ca.key",
    "-tls1_3", "-groups", "mlkem768", "-www", "-accept", "4433"
]
server_proc = subprocess.Popen(server_cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
print("1. Quantum Server listening on port 4433...")

# 3. Start Packet Capture
# -U (packet-buffered) prevents the "Broken Pipe" error by flushing data immediately
print("2. Starting Packet Capture (tcpdump)...")
cap_cmd = ["tcpdump", "-i", "lo", "-U", "-w", "quantum_data.pcap", "port", "4433"]
cap_proc = subprocess.Popen(cap_cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
time.sleep(2)

# 4. Generate Traffic
print("3. Simulating 50 Quantum Handshakes...")
for i in range(50):
    # s_client connects, performs the handshake, and immediately exits
    os.system("openssl s_client -connect localhost:4433 -provider oqsprovider -provider default -groups mlkem768 -brief < /dev/null > /dev/null 2>&1")
    if (i+1) % 10 == 0:
        print(f"   Progress: {i+1}/50 handshakes complete")

# 5. Safe Shutdown
print("4. Finalizing and saving data...")
time.sleep(3) # Wait for the last packets to finish traversing the pipe

# 5. Safe Shutdown
print("4. Finalizing and saving data...")
time.sleep(3) # Wait for the last packets to finish traversing the pipe

# Terminate processes gracefully
cap_proc.terminate()
server_proc.terminate()

# Wait for tcpdump to finish writing the .pcap file
try:
    cap_proc.wait(timeout=5)
    print("5. Success! 'quantum_data.pcap' is ready for analysis.")
except subprocess.TimeoutExpired:
    cap_proc.kill()
    print("5. Capture process forced to stop. Checking file...")

# Verify file size
size = os.path.getsize("quantum_data.pcap")
print(f"Final file size: {size / 1024:.2f} KB")

import subprocess
import time
import os

# 1. Cleanup: Kill any lingering processes
os.system("pkill -9 openssl")
os.system("pkill -9 tcpdump")
time.sleep(1)

print("--- Starting Classical (Attack) Simulation ---")

# 2. Start the Server using a CLASSICAL group (x25519)
# This simulates traffic that is NOT quantum-resistant
server_cmd = [
    "openssl", "s_server",
    "-cert", "pqc_ca.crt", "-key", "pqc_ca.key",
    "-tls1_3", "-groups", "x25519", "-www", "-accept", "4433"
]
server_proc = subprocess.Popen(server_cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
print("1. Classical Server listening on port 4433...")

# 3. Start Packet Capture for the "Classical" file
print("2. Starting Packet Capture (classical_data.pcap)...")
cap_proc = subprocess.Popen(["tcpdump", "-i", "lo", "-U", "-w", "classical_data.pcap", "port", "4433"])
time.sleep(2)

# 4. Generate 50 Classical Handshakes
print("3. Simulating 50 Classical (Vulnerable) Handshakes...")
for i in range(50):
    # Using x25519 instead of mlkem768
    os.system("openssl s_client -connect localhost:4433 -groups x25519 -brief < /dev/null > /dev/null 2>&1")
    if (i+1) % 10 == 0:
        print(f"   Progress: {i+1}/50 complete")

# 5. Shutdown
time.sleep(3)
cap_proc.terminate()
server_proc.terminate()

print("--- Done! 'classical_data.pcap' created successfully ---")

!tcpdump -X -r quantum_data.pcap | head -n 20

!pip install scapy

from scapy.all import rdpcap, IP, TCP
import pandas as pd

def extract_features(pcap_file):
    packets = rdpcap(pcap_file)
    data = []

    # We group packets into "Flows" (source -> destination)
    # For this lab, we just extract per-packet statistics
    for i, pkt in enumerate(packets):
        if IP in pkt and TCP in pkt:
            feature_row = {
                "packet_index": i,
                "src_ip": pkt[IP].src,
                "dst_ip": pkt[IP].dst,
                "length": len(pkt),
                "timestamp": float(pkt.time),
                "tcp_flags": int(pkt[TCP].flags),
                "payload_size": len(pkt[TCP].payload)
            }
            data.append(feature_row)

    return pd.DataFrame(data)

# Run extraction
df = extract_features("quantum_data.pcap")

# Calculate "Inter-Arrival Time" (IAT) - crucial for PQC timing analysis
df['iat'] = df['timestamp'].diff().fillna(0)

print(df.head())
df.to_csv("pqc_features.csv", index=False)

# 1. Process the Quantum Data
print("Extracting Quantum features...")
df_quantum = extract_features("quantum_data.pcap")
df_quantum['iat'] = df_quantum['timestamp'].diff().fillna(0)
df_quantum['label'] = 1  # 1 = Safe/Quantum-Ready

# 2. Process the Classical Data
print("Extracting Classical (Attack) features...")
df_attack = extract_features("classical_data.pcap")
df_attack['iat'] = df_attack['timestamp'].diff().fillna(0)
df_attack['label'] = 0  # 0 = Vulnerable/Potential Attack

# 3. Combine into a Master Dataset
df_final = pd.concat([df_quantum, df_attack], ignore_index=True)

# 4. Shuffle the data
# This is critical so the model doesn't learn based on the order of rows
df_final = df_final.sample(frac=1).reset_index(drop=True)

# 5. Final Check
print(f"Success! Final dataset contains {len(df_final)} packets.")
print(df_final['label'].value_counts()) # Should show a balance of 0s and 1s
df_final.to_csv("ids_master_dataset.csv", index=False)

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import pandas as pd

# 1. Select the features the AI will look at
# We exclude IP addresses and timestamps because those change.
# We focus on the 'physics' of the packet.
features = ['length', 'payload_size', 'iat', 'tcp_flags']
X = df_final[features]
y = df_final['label']

# 2. Split into Training (80%) and Testing (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Create and Train the Random Forest
# n_estimators=100 means we are using 100 "Decision Trees" to vote on the result
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

print("--- IDS Model Training Complete ---")

# 4. Make predictions on the test set
y_pred = clf.predict(X_test)

# 5. Show the Accuracy Report
print("\n--- Performance Report ---")
print(classification_report(y_test, y_pred, target_names=['Attack (Classical)', 'Safe (Quantum)']))

# 6. Visualize the Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Attack', 'Safe'])
disp.plot(cmap='Blues')
plt.title('Quantum IDS: Detection Results')
plt.show()

import pandas as pd
import seaborn as sns

# Get the importance scores
importances = clf.feature_importances_
feat_importances = pd.Series(importances, index=features)

# Plot
plt.figure(figsize=(10,5))
feat_importances.nlargest(4).plot(kind='barh', color='teal')
plt.title('Which Packet Feature is the Best Quantum Indicator?')
plt.xlabel('Importance Score')
plt.show()

import joblib
joblib.dump(clf, 'pqc_ids_model.pkl')
print("Model saved as pqc_ids_model.pkl")

